branch-defaults:
  default:
    environment: null
    group_suffix: null
global:
  application_name: udagram-baer-dev
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js running on 64bit Amazon Linux
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
